### ISSUE TITLE
code loading failed

### ISSUE THREAD

**Issue by martijn41s** [kbaskett248/adafruit_macropad#15]
I tried importing the code to my macropad with circuitpython 7.3.1 but it fails
Updating the libraries did not help unfortunatly.
```
Auto-reload is on. Simply save files over USB to run them or enter REPL to disable.
code.py output:
Traceback (most recent call last):
  File "code.py", line 16, in <module>
  File "utils/app_pad.py", line 175, in __init__
  File "utils/app_pad.py", line 189, in _init_macropad
  File "adafruit_macropad.py", line 172, in __init__
IndexError: tuple index out of range
```

**Comment by martijn41s** [comment]
Sorry, I solved it by enabling the MIDI device again.
I have also disabled the USB drive on boot unless the encoder button is pressed.
Is this something that could be worthwhile to add to the code?
